# Generated by Django 4.1 on 2022-08-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('titre', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/img/posts')),
                ('description', models.TextField()),
            ],
        ),
    ]
