# Generated by Django 4.1 on 2022-08-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0003_rename_posts_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='titre',
            field=models.CharField(max_length=500),
        ),
    ]
