# Generated by Django 4.1 on 2022-08-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0004_alter_post_titre'),
    ]

    operations = [
        migrations.CreateModel(
            name='resSport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_Prenom', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Nbr_Personne', models.IntegerField()),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('Tel', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='compte',
            name='password',
            field=models.CharField(max_length=10),
        ),
    ]
