# Generated by Django 4.1 on 2022-08-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0005_ressport_alter_compte_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='resRestauration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_Prenom', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Nbr_Personne', models.IntegerField()),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('Tel', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='ressport',
            name='Nbr_Personne',
        ),
        migrations.AddField(
            model_name='ressport',
            name='activite',
            field=models.CharField(default='DEFAULT VALUE', max_length=100),
        ),
    ]
