# Generated by Django 4.1 on 2022-08-16 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0006_resrestauration_remove_ressport_nbr_personne_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compte',
            name='username',
            field=models.CharField(default='DEFAULT VALUE', max_length=10),
        ),
    ]
