# Generated by Django 4.1 on 2022-08-20 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0007_compte_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='resrestauration',
            name='typeres',
            field=models.CharField(default='Restauration', max_length=10),
        ),
        migrations.AddField(
            model_name='ressport',
            name='typeres',
            field=models.CharField(default='Activité sportif', max_length=10),
        ),
    ]
