# Generated by Django 4.1 on 2022-08-20 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0008_resrestauration_typeres_ressport_typeres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resrestauration',
            name='typeres',
            field=models.CharField(default='Restauration', max_length=100),
        ),
        migrations.AlterField(
            model_name='ressport',
            name='typeres',
            field=models.CharField(default='Activité sportif', max_length=100),
        ),
    ]
