# Generated by Django 4.1 on 2022-09-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0013_alter_post_date_alter_resrestauration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default='AAAA-MM-JJ'),
        ),
    ]
