# Generated by Django 4.1 on 2022-09-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0014_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default='aaaa-mm-jj'),
        ),
        migrations.AlterField(
            model_name='resrestauration',
            name='date',
            field=models.DateField(default='aaaa-mm-jj'),
        ),
    ]
