# Generated by Django 4.1 on 2022-09-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0015_alter_post_date_alter_resrestauration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resrestauration',
            name='heure',
            field=models.TimeField(default='hh:mm:ss'),
        ),
        migrations.AlterField(
            model_name='ressport',
            name='date',
            field=models.DateField(default='aaaa-mm-jj'),
        ),
        migrations.AlterField(
            model_name='ressport',
            name='heure',
            field=models.TimeField(default='hh:mm:ss'),
        ),
    ]
